"""Add contract plans table

Revision ID: add_contract_plans
Revises: 4544e6388dcb
Create Date: 2025-04-28 12:15:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_contract_plans'
down_revision = '4544e6388dcb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contract_plans',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=64), nullable=False),
        sa.Column('type', sa.String(length=20), nullable=False),
        sa.Column('hashrate', sa.Integer(), nullable=False),
        sa.Column('duration', sa.Integer(), nullable=False),
        sa.Column('price_usd', sa.Float(), nullable=False),
        sa.Column('price_btc', sa.Float(), nullable=False),
        sa.Column('maintenance_fee', sa.Float(), nullable=False),
        sa.Column('is_active', sa.Boolean(), default=True),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contract_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contract_plans_name'), ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contract_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contract_plans_name'))

    op.drop_table('contract_plans')
    # ### end Alembic commands ### 