name: Деплой приложения

on:
  push:
    branches: [ main, master ]
    tags:
      - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/v')
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Настройка Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Установка зависимостей
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Запуск тестов перед деплоем
      run: |
        pytest
    
    - name: Настройка SSH
      uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    
    - name: Деплой на сервер
      run: |
        # Добавление сервера в известные хосты
        mkdir -p ~/.ssh
        ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts
        
        # Подготовка папки для деплоя
        rsync -avz --exclude '.git' \
              --exclude 'venv' \
              --exclude '.env' \
              --exclude '__pycache__' \
              --exclude '*.pyc' \
              --exclude '.pytest_cache' \
              --exclude 'htmlcov' \
              ./ ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:${{ secrets.SERVER_PATH }}
        
        # Выполнение команд на сервере
        ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} "cd ${{ secrets.SERVER_PATH }} && \
                python -m venv venv || true && \
                source venv/bin/activate && \
                pip install --upgrade pip && \
                pip install -r requirements.txt && \
                flask db upgrade && \
                sudo systemctl restart flask_app"

  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Настройка Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Установка зависимостей
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Запуск тестов
      run: |
        pytest 